---
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 0
  commit-message:
    prefix: actions
  rebase-strategy: auto
  ignore:
  - dependency-name: "*"
    update-types:
    - version-update:semver-major